defaults:
  - _self_
  - benchmark: librispeech
device: cuda
model: small
input: ./data
output: ./transcribtion
available_models: [tiny.en, tiny, base, base.en, base, small.en, small, medium.en, medium, large]
greet_message: "Hello AI "
batch_size: 64
num_workers: 12
decode_options:
  task: transcribe
  temperature: 0.5
  best_of: 10
  fp16: true
  verbose: false
  beam_size: null